### ISSUE TITLE
Internal Server Error with version 0.9.0

### ISSUE THREAD

**Issue by dnyamy** [haru/redmine_code_review#15]
Hello,
I am having troubles to get the plugin work with my Redmine Install
I use Redmine 3.4 in production

The plugin installed well and I can see it in the plugin list

But when I try to configure a project by clicking the configuration tab, I get an internal error

`Started GET "/projects/myprojectname/settings" for 80.214.115.115 at 2019-01-24 19:35:05 +0100
Processing by ProjectsController#settings as HTML
Parameters: {"id"=>"myprojectname"}
Current user: dnyamy (id=5)
Rendered projects/settings.html.erb within layouts/base (137.6ms)
Completed 500 Internal Server Error in 167ms (ActiveRecord: 15.7ms)

ActionView::Template::Error (super: no superclass method project_settings_tabs' for #<#<Class:0x007ff0532e8010>:0x007ff052ee7510> Did you mean? project_settings_tabs_with_code_review): 
1: <h-><%=l(:label_settings)%></h2> 
2: 
3: <%= render_tabs project_settings_tabs %> 
4: 
5: <% html_title(l(:label_settings)) -%> plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in project_settings_tabs'
plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:35:in project_settings_tabs_with_code_review' plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in project_settings_tabs'
app/views/projects/settings.html.erb:3:in _app_views_projects_settings_html_erb___3567123408715600042_70335077502180' lib/redmine/sudo_mode.rb:63:in sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in call'

There seems to be an incompatibility with another plugin I have: redmine_dmsf

Please can some body advise ?

Thanks
Dorice

**Comment by dskibarko** [comment]
Seems worked fine on Redmine 3.4.5 then was changed line of Init.rb to
requires_redmine :version_or_higher => '3.4.0' instead of line 
requires_redmine :version_or_higher => '4.0.0'

**Comment by dnyamy** [comment]
Problem solved
At last
It was indeed a conflict, with redmine dmsf plugin
Fixed by following commit :
https://github.com/danmunn/redmine_dmsf/commit/689b2dc7930eca92a89c839070b2e79b8e461c6d
