### ISSUE TITLE
code review dosen't work with redmine_banner

### ISSUE THREAD

**Issue by hiroshi24da** [haru/redmine_code_review#19]
Hello.

I tried code review on redmine 4.1.0,
and couldn't write review because pencil icons don't appear when installed with banner.
It works without banner.

redmine 4.1.0
redmine_code_review 1.0.0
redmine_banner 0.3.0

**Comment by haru** [comment]
I tried to reproduce with as same as your environment: redmine 4.1.0, code_review 1.0.0, banner 0.3.0.
But I can't be reproduced. Pencil icons were appeared.

![image](https://user-images.githubusercontent.com/99401/73717987-9f19fd80-475e-11ea-9fa9-59bba704dfba.png)


Does any javascript error appear in your browser's developer console?

**Comment by hiroshi24da** [comment]
Sory, it depends on browser.
It works on chrome, but doesn't on firefox.

**Comment by hiroshi24da** [comment]
And it works on both chrome and firefox on redmine3.4.4, code_review0.9.0, banner0.1.2

**Comment by haru** [comment]
Hmm. It works fine with my firefox.
Can you try clear cache?

**Comment by hiroshi24da** [comment]
Cash clear don't work...
It seems that there are banner related javascript errors,
but there's no code review related error.
![javascript_error](https://user-images.githubusercontent.com/34000091/73723515-8d3f5700-476c-11ea-9985-eba799a2c12e.png)

**Comment by haru** [comment]
Does following file exist in your Redmine installation directory?
`public/plugin_assets/redmine_banner/javascripts/banner.js`

**Comment by hiroshi24da** [comment]
banner.js exists.
and... resolved !

(1) redmine4.1.0 + code review + banner + firefox > works
(2) redmine4.1.0 + code review + banner + firefox + _AdBlock_ > doesn't work

I wonder why (2) works on redmine3.4.4.
Anyway it works.
Thanks for your help and great plugin.

**Comment by akiko-pusu** [comment]
@haru Thanks for your support!
